import type { Metadata } from "next";
import {Urbanist} from "next/font/google";
import "./globals.css";

export const urbanist = Urbanist({
  subsets: ['latin'],
  // weights: ['400', '700'], // You can specify the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={urbanist.className}
      >
        {children}
      </body>
    </html>
  );
}
